// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $analyze from "./routes/analyze.ts";
import * as $api_mistrall from "./routes/api/mistrall.ts";
import * as $api_pagespeedd from "./routes/api/pagespeedd.ts";
import * as $index from "./routes/index.tsx";
import * as $FormIsland from "./islands/FormIsland.tsx";
import * as $InfoTooltipsIsland from "./islands/InfoTooltipsIsland.tsx";
import * as $Modulo1_LoadingDonut from "./islands/Modulo1/LoadingDonut.tsx";
import * as $Modulo1_ResultCard from "./islands/Modulo1/ResultCard.tsx";
import * as $Modulo1_TechnicalAnalysisModule from "./islands/Modulo1/TechnicalAnalysisModule.tsx";
import * as $Modulo2_LowVisionIsland from "./islands/Modulo2/LowVisionIsland.tsx";
import * as $Modulo2_ResultsAxe from "./islands/Modulo2/ResultsAxe.tsx";
import * as $Modulo2_ScreenReaderIsland from "./islands/Modulo2/ScreenReaderIsland.tsx";
import * as $Modulo2_SeniorVisionIsland from "./islands/Modulo2/SeniorVisionIsland.tsx";
import * as $Modulo2_SimulationModule from "./islands/Modulo2/SimulationModule.tsx";
import * as $Modulo3_HeuristicModule from "./islands/Modulo3/HeuristicModule.tsx";
import * as $Modulo4_RecommendationsModule from "./islands/Modulo4/RecommendationsModule.tsx";
import * as $Modulo5_FinalModule from "./islands/Modulo5/FinalModule.tsx";
import * as $UXAdvisorApp from "./islands/UXAdvisorApp.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/analyze.ts": $analyze,
    "./routes/api/mistrall.ts": $api_mistrall,
    "./routes/api/pagespeedd.ts": $api_pagespeedd,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/FormIsland.tsx": $FormIsland,
    "./islands/InfoTooltipsIsland.tsx": $InfoTooltipsIsland,
    "./islands/Modulo1/LoadingDonut.tsx": $Modulo1_LoadingDonut,
    "./islands/Modulo1/ResultCard.tsx": $Modulo1_ResultCard,
    "./islands/Modulo1/TechnicalAnalysisModule.tsx":
      $Modulo1_TechnicalAnalysisModule,
    "./islands/Modulo2/LowVisionIsland.tsx": $Modulo2_LowVisionIsland,
    "./islands/Modulo2/ResultsAxe.tsx": $Modulo2_ResultsAxe,
    "./islands/Modulo2/ScreenReaderIsland.tsx": $Modulo2_ScreenReaderIsland,
    "./islands/Modulo2/SeniorVisionIsland.tsx": $Modulo2_SeniorVisionIsland,
    "./islands/Modulo2/SimulationModule.tsx": $Modulo2_SimulationModule,
    "./islands/Modulo3/HeuristicModule.tsx": $Modulo3_HeuristicModule,
    "./islands/Modulo4/RecommendationsModule.tsx":
      $Modulo4_RecommendationsModule,
    "./islands/Modulo5/FinalModule.tsx": $Modulo5_FinalModule,
    "./islands/UXAdvisorApp.tsx": $UXAdvisorApp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
